### ISSUE TITLE
Can't Use Intellij IDEA 15.0.2

### ISSUE THREAD

**Issue by melito00** [adobe-fonts/source-han-code-jp#10]
This fonts are not visible on "Font List".
Please refer to "http://qiita.com/shiena/items/70ba503fd2db4936f240"

**Comment by miguelsousa** [comment]
It's an IntelliJ bug. It doesn't seem to support OpenType/CFF fonts.
See also https://github.com/adobe-fonts/source-han-sans/issues/130
