### ISSUE TITLE
Glyph width of U+2423 OPEN BOX '␣'

### ISSUE THREAD

**Issue by mashabow** [adobe-fonts/source-han-code-jp#12]
This is a suggestion to change the glyph width of U+2423 OPEN BOX `␣`.

U+2423 is often used to visualize U+0020 SPACE, e.g.:

```
インデントはスペース4つにしてください。

for glyph in font:
␣␣␣␣if not glyph.name:
␣␣␣␣␣␣␣␣glyph.name = 'NoName'
```

In Source Han Code JP, however, the glyph width of U+2423 is 1000 units, while that of U+0020 is 667 units.

<img alt="screenshot" src="https://cloud.githubusercontent.com/assets/6268183/14177502/87aa321c-f791-11e5-886f-c0e9b5b99fe8.png">

 I suggest to change its width from 1000 units to 667 units.

**Comment by kenlunde** [comment]
On a somewhat related note, would it be useful to add a half-width version of U+2423 (uni2423-HW) to [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/) to accompany half-width ASCII + yen + won (uni0020-HW through uni007E-HW + uni00A5-HW + uni20A9-HW)? These would be accessible via the 'hwid' GSUB feature or via the "HW" versions of the fonts.

**Comment by hatchzo** [comment]
OK, I will add that to my note for the next update.

**Comment by hatchzo** [comment]
I changed the advance of U+2423 OPEN BOX ␣ from 1000 units to 667 unites on version 2.010.
