### ISSUE TITLE
Light/cidfontinfo is missing

### ISSUE THREAD

**Issue by mashabow** [adobe-fonts/source-han-code-jp#13]
I found there are no `cidfontinfo` file in the [Light](https://github.com/adobe-fonts/source-han-code-jp/tree/c1064e6db2c13bf57516a1861e37267220e1fbe4/Light) directory. Besides, there is an unnecessary file `cidfont.ps`.

**Comment by hatchzo** [comment]
Sorry for the inconvenience, I fixed them right now.
