### ISSUE TITLE
Add Japanese era REIWA support

### ISSUE THREAD

**Issue by KiYugadgeter** [adobe-fonts/source-han-code-jp#16]
Add Japanese new era reiwa that U+32FF

**Comment by kenlunde** [comment]
Use [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/).

**Comment by kenlunde** [comment]
…or the forthcoming _Source Han Mono_. 🤫

**Comment by kenlunde** [comment]
[_Source Han Mono_](https://github.com/adobe-fonts/source-han-mono) was just released.
