### ISSUE TITLE
The font is always black after upgrading Big Sur

### ISSUE THREAD

**Issue by goiwai** [adobe-fonts/source-han-code-jp#17]
As a derivative Source Code Pro, the issue affects on Source Han Code JP too. Take a look at:
https://github.com/microsoft/vscode/issues/100840#issuecomment-729641258

**Comment by punchcutter** [comment]
This is because of the way the SVG table is handled. We have removed it from the latest release of Source Code Pro to avoid this issue, but haven't done a new release of Source Han Code JP yet. I'll make one now.

**Comment by goiwai** [comment]
謝謝🙇 Thank you for looking into this. The latest Source Code Pro is working perfectly for me, and it is a tentative workaround. However, Japanese characters in the code are all blackout 🤣

**Comment by punchcutter** [comment]
The latest release should work now. https://github.com/adobe-fonts/source-han-code-jp/releases/tag/2.012R

**Comment by goiwai** [comment]
謝謝🙇 The latest release (2.012R) is working fine on Big Sur. I got the syntax highlighting feature back.
