### ISSUE TITLE
window10のIntellijで、使用できない。

### ISSUE THREAD

**Issue by pauloil** [adobe-fonts/source-han-code-jp#18]
＜環境＞
System: Windows 10 HOME 1909
Intellij: IntelliJ IDEA 2020.3.1 (Community Edition)
＜事象＞
Windowsでご提供いただいた最新バージョンをインストールし、Intellijで、該当Fontの選択がありませんでした。

ちなみに、Mac Big surのintellijで、問題なく使用できます。

**Comment by hatchzo** [comment]
もしまだ試していなければ、フォントをインストールするときに、右クリックで「すべてのユーザーに対してインストール」を選んで、確認していただけませんか？

**Comment by pauloil** [comment]
ご回答ありがとうございます。

ご提示いただいた方法で、うまくできました。
ありがとうございます。
![image](https://user-images.githubusercontent.com/48395533/105185002-5f1c7800-5b73-11eb-8f3f-b4542685c2c5.png)
