### ISSUE TITLE
Support for Traditional Chinese(Taiwan) glyphs?

### ISSUE THREAD

**Issue by Vdragon** [adobe-fonts/source-han-code-jp#2]
Hi, it's really great to find out there's a monospaced Source Han Sans based font, is it possible to extend the support to Traditional Chinese(Taiwan) glyphs?

**Comment by hatchzo** [comment]
Yes, It will be possible to make Traditional Chinese or PanCJK font with monospaced Latin glyphs.  
However, I could not have any engagement to do so.

**Comment by kenlunde** [comment]
@Vdragon: You can also try using the [Source Han Sans Traditional Chinese HW fonts](https://github.com/adobe-fonts/source-han-sans/tree/release/OTF/TraditionalChineseHW), which use half-width forms of ASCII (U+0020 through U+007E).

**Comment by s8321414** [comment]
Any chance to derive whole source-han-sans to source-han-code font set? :smiley:

**Comment by kenlunde** [comment]
@s8321414: Of course, this can be considered, and is [not outside the realm of extreme possibilities](http://en.wikipedia.org/wiki/Fox_Mulder).

**Comment by ShikiSuen** [comment]
You could use FontForge to make it by yourself. They are all CID fonts.
You simply open Source Han Sans TW and replace its Latin part with all glyphs come from Source Han Code JP.

**Comment by kenlunde** [comment]
I am starting to work on a Pan-CJK version of this excellent typeface. I will coordinate with @hatchzo on many of the particulars. Stay tuned.

**Comment by kenlunde** [comment]
I am within [two weeks](https://www.youtube.com/watch?v=XY5KTVA_2ys) of releasing _Source Han Mono_, which is a full-blown Pan-CJK version of _Source Han Code JP_. It will be deployed only as a 70-font OpenType/CFF Collection. The non-Western portion will be aligned with _Source Han Sans_ Version 2.001, warts and all. I adjusted only two CJK-related mappings.

**Comment by kenlunde** [comment]
[_Source Han Mono_](https://github.com/adobe-fonts/source-han-mono) was just released.
