### ISSUE TITLE
Contains unwanted ligatures

### ISSUE THREAD

**Issue by mm-jikasei** [adobe-fonts/source-han-code-jp#4]
![ligatures](https://cloud.githubusercontent.com/assets/12693275/8164357/81614470-13c3-11e5-83bf-7b2c1f0fae86.png)

このフォントには、Source code pro と違い「fi」や「fl」などのリガチャが含まれていて、
Visual Studio や Xcode などで合字になってしまいます。これはおそらく不必要かと思われます。

This font contains unwanted ligatures of "fi", "fl" etc.

**Comment by kenlunde** [comment]
Although there is no open issue for this yet, this ligature issue is known, and @hatchzo plans to fix it in the next version.

**Comment by mm-jikasei** [comment]
Okay, Thanks!

**Comment by kenlunde** [comment]
Fixed in Version 1.004.

**Comment by methane** [comment]
Is this really fixed?
![screenshot](https://cloud.githubusercontent.com/assets/199592/24695354/65e5cfe4-1a20-11e7-822f-29a7dbf6a38e.png)

fi seems ligatured even in version 2.000

**Comment by hatchzo** [comment]
Probably, you do not use version2.000, because weight names have been changed from a full-length word to just an inital since version 1.004, e.g. “Regular” to “R”.

**Comment by methane** [comment]
You're right.  Thanks.
