### ISSUE TITLE
Why not using attached binaries on release?

### ISSUE THREAD

**Issue by kakkun61** [adobe-fonts/source-han-code-jp#7]
If you know it and you choose current way on purpose, I'm sorry.

You are using “release” branch to distribute OTF & OTC files and sources are on “master” branch. However you need not to use “release” branch if you use “attach binaries” function on releases.

How to use:
1. go to [edit page](https://github.com/adobe-fonts/source-han-code-jp/releases/new?tag=1.004) of release
2. drag and drop OTC, OTF files to the area like below
3. and then users can download the files on [release page](https://github.com/adobe-fonts/source-han-code-jp/releases/tag/1.004)

![attach-binaries](https://cloud.githubusercontent.com/assets/282593/8528638/34c23b64-244f-11e5-91fa-1359b49f004f.png)

**Comment by miguelsousa** [comment]
@kakkun61 we know about the "Attach binaries" field. We have the font binaries in a `release` branch because we want to keep them under version control and because we need access to the font files beyond a download link in the Releases page.
